### ISSUE TITLE
Request: Bargraph

### ISSUE THREAD

**Issue by krangerich** [hneemann/Digital#1086]
It would be nice to have a bargraph component. 

While you could use single LEDs instead, a bargraph has its advantages: 
- You only have add one component instead of like 8
- Takes less space, because you have to place single LEDs every 2 grid lines. Inputs of a bargraph should be 1 grid line apart.
- It just looks nicer, e.g. when visualizing CPU registers

Number of bars should be configurable (e.g. 4, 8, 10, 16)

**Comment by xotmatrix** [comment]
One can change the size of the LED so that it only takes up one grid space. Constructing a group of LED is not that difficult but a bar graph display could be convenient. Alternatively, I sometimes wish it was possible to define groups of components to make selecting all of them easier.

![javaw_2022-12-29_14-07-32](https://user-images.githubusercontent.com/14209329/209997816-769dc6d4-bf36-432c-80e7-937fda8dde63.png)

**Comment by hneemann** [comment]
Since the suggestion of @xotmatrix is sufficient in my opinion, I close this issue.
