### ISSUE TITLE
Nothing connected to input 'In_1' at component 'And'

### ISSUE THREAD

**Issue by clamintus** [hneemann/Digital#1226]
Hi, I'm trying to implement a finite-state machine, but sadly I'm not able to simulate my circuit.
![image](https://github.com/hneemann/Digital/assets/44071820/33514f4a-3fad-4484-9b2d-e40123ad8312)
Every time I try to start the simulation, one of the AND components complains it has nothing connected to it, even though all the inputs are clearly connected.
If I try removing the component and then placing it there again, the error just moves on to other AND components I have in the circuit.
I'm not able to find out what's wrong in my circuit, everything seems OK to me.

**Comment by clamintus** [comment]
Here is my project file in case you need it: [Reti_sequenziali 1.tar.gz](https://github.com/hneemann/Digital/files/13193807/Reti_sequenziali.1.tar.gz)

**Comment by hneemann** [comment]
A wire must end at a pin to make a connection. 
There is another problem in the circuit: there must be only one active output connected to a wire. If two outputs are connected to one wire, what happens when one goes high and the other goes low? In a real circuit, one of the outputs would be destroyed by an overcurrent.

I have corrected the wires that are not connected: [Reti_sequenziali 1.dig.zip](https://github.com/hneemann/Digital/files/13194498/Reti_sequenziali.1.dig.zip)
