### ISSUE TITLE
ROM program memory

### ISSUE THREAD

**Issue by angusbonney** [hneemann/Digital#1329]
So you can set a ROM to be program memory so it can be accessed by an external IDE but how do you do this?

**Comment by hneemann** [comment]
There are two possibilities: You can have a file loaded automatically every time you start the simulation so that every change to the file is applied the next time you start the simulation. Or you can use a TCP/IP interface via which the simulator can be controlled remotely. The function can be derived from this [code](https://github.com/hneemann/Digital/blob/master/src/main/java/de/neemann/digital/gui/remote/DigitalHandler.java).
An example can be found [here](https://github.com/hneemann/Assembler/blob/master/src/main/java/de/neemann/assembler/gui/RemoteInterface.java).
