### ISSUE TITLE
74165 : strange behaviour (2)

### ISSUE THREAD

**Issue by gnaghi** [hneemann/Digital#1361]
Hi. I've modified the 74165 schematic (I've taken the comment of https://github.com/hneemann/Digital/issues/1084 into account), and each time I launch the simulation, I get a different behavior.
Latch is set to active low.
When I start simulation, QH and /QH changes level, even if no input from A to H is set to high, and Latch is high (the button is not pressed).

![img1](https://github.com/user-attachments/assets/bdf19d1a-c345-49f7-9a56-69e9f37fb96a)
![img2](https://github.com/user-attachments/assets/dcf75290-6dfa-4452-8983-a0b642084500)
![img3](https://github.com/user-attachments/assets/84444afe-380f-4e40-83e3-74bc17e7121b)
![img4](https://github.com/user-attachments/assets/58e14f7e-59e1-47b1-a200-f64879dd44c6)

**Comment by mengstr** [comment]
It seems like the individual D-flops start starts up in a randomised state due to the propagation delay by the inverter in front of the nSET input.  The first circuit in my test circuit starts with a random value, the second always starts the same.

As I remember it a real 74165 also starts up with the internal databits randomised (as many other 74-series ICs)  - so I guess the sim works just as the real part, even if this random effect here was maybe not intentional made. ;-)

<img width="432" alt="Screenshot 2024-11-07 at 21 58 20" src="https://github.com/user-attachments/assets/5bfb9d1e-02e1-4984-9414-0a1cf87430c9">

**Comment by hneemann** [comment]
@mengstr 
This behavior is actually intentional! :-)

It is necessary to prevent circuits from oscillating directly during initialization. When a circuit is started, the first calculation of all gates takes place in random order. This always leads to a stable state and is also quite similar to the behavior of a real circuit without a reset logic.
