### ISSUE TITLE
Selectable display style for 74xx lib parts

### ISSUE THREAD

**Issue by dfbg** [hneemann/Digital#147]
I am doing a lot of designing using the library parts but I much prefer a schematic style layout rather than an actual IC layout.

I suggest a checkbox in the circuit instance attributes to select the style.  It might require two width settings in the embedded circuit attributes so each version looks best.

It would also be nice if the VCC and GND inputs were automatically hooked up and hidden in schematic mode (or maybe it's also a checkbox).  Just to reduce visual noise.

**Comment by hneemann** [comment]
@dfbg 
The current architecture does not allow to have different shapes in different circuits for the same subcircuit. Its only possible to change the shape globally. And this is a problem because if this global setting is set to a certain value it might be that a circuit does not work if it was created with an other setting.
The round/rectangular shape switch only works because the pin positions are the same in both shapes.
It would take a lot of work to implement that. I think it's not worth the effort.

**Comment by hneemann** [comment]
@dfbg 
I thought about it: It is difficult to change the shape with a single setting for several circuits. 
But it is easy to select it separately for each circuit.
Please try the latest [pre release](https://infdigital.dhbw-mosbach.de/) build v0.18-58.
It was necessary to change the meaning of the width setting in a DIL shape. Therefore it is necessary to change the width setting in your own DIL circuits.

**Comment by dfbg** [comment]
That's what I was hoping for.  A simple per-instance checkbox.

Is it possible to hide the power inputs in schematic mode when they're only connected to the "Power" box in the sub-circuit?  That's a good indicator that not connecting them won't fail.  Just to reduce the clutter of having Vcc and Gnd inputs on every part.

**Comment by hneemann** [comment]
There is no easy way to do that. Sorry for that!
