### ISSUE TITLE
Support ASCII control characters, allow Terminal and Keyboard to be re-opened

### ISSUE THREAD

**Issue by elijahlorden** [hneemann/Digital#171]
It would be nice if the Terminal could support the backspace (ASCII 8) and form-feed (ASCII 12) characters.  In my testing, 8 and 12 are just appended to the terminal output.

If the Terminal or Keyboard are closed, it is not possible to re-open them without restarting the simulation.  being able to re-open them by clicking on the component or through some other means (perhaps a list of keyboards/terminals for the current simulation) seems like it should be doable.

**Comment by hneemann** [comment]
The Terminal is reopened automatically as soon as a new character is written to it.
And the keyboard dialog has a rather complex relationship to the models keyboard component. thus a reopening is not so easy.
And from my understanding a workaround is simple: Don't close the dialog.
That's why I do not want to implement that.
