### ISSUE TITLE
Brazilian Portuguese translation of static.xml

### ISSUE THREAD

**Issue by crcpucmg** [hneemann/Digital#245]
Attached translation of static_pt.xml for documentation purposes.
[static_pt.zip](https://github.com/hneemann/Digital/files/2870945/static_pt.zip)

**Comment by hneemann** [comment]
@crcpucmg 
Are you sure you have attached a file?

**Comment by crcpucmg** [comment]
It's uploaded now: static_pt.zip.

Please, check.

Em qui, 14 de fev de 2019 às 05:11, Helmut Neemann <notifications@github.com>
escreveu:

**Comment by hneemann** [comment]
I had some problems using the attached file because the encoding specified in the header does not match the encoding used in the file itself. I have trans coded the file from ISO 8859-1 (which I think is the default encoding used on Portuguese windows machines) to UTF-8 and hopefully it worked. To me it looks fine.
Perhaps you can also have a look at the attached PDF file: [Doc_Portuguese.pdf.zip](https://github.com/hneemann/Digital/files/2871763/Doc_Portuguese.pdf.zip)
