### ISSUE TITLE
why the build in logic gate think of high z as 0

### ISSUE THREAD

**Issue by itviewer** [hneemann/Digital#246]
for example the Not gate,
![1](https://user-images.githubusercontent.com/1397840/52911216-c53f5700-32db-11e9-9d74-8c01fe2ce0bc.png)

The Not gate build with pmos and nmos transistors I learned from the textbook,
![1](https://user-images.githubusercontent.com/1397840/52911257-4e568e00-32dc-11e9-9659-5993f9b29985.png)
all built-in logic gates pull high z down to ground?  Is this the case in a real circuit?

**Comment by hneemann** [comment]
No! The behavior of a real circuit depends on the technology used to implement the gates.
In your example of a typical CMOS implementation, a high Z input is dangerous and should be avoided. Due to the high input impedance of the FET gates, the input may drift to an intermediate voltage, making both the n-channel and p-channel transistors conductive. This can lead to a high current flow and damage the circuit. (See also [here](https://github.com/hneemann/Digital/issues/36#issuecomment-315969098))
In old chips which use TTL technology (multi-emitter bipolar transistors) a open input is interpreted as connected to high. I think that's why you often find a pullup resistor at CMOS inputs. The input then behaves like an old TTL input. But also a large pullup resistor increases the power consumption.

In Digital, all gates that are not specifically designed to deal with a high-z input read a high-z input as connected to zero.  But this has more programming reasons, because it makes some things easier to implement. Simply spoken: You can't draw current from a high-z input, so a LED stays dark. As if it were connected to zero.

**Comment by itviewer** [comment]
thanks.
I now suspect that if we are not familiar with the physical characteristics of the Transistor devices, can we really design the digital circuit.

**Comment by hneemann** [comment]
I think if a real chip is planned to have unconnected inputs, it's a good idea to consult the datasheet to check whether that's allowed or not.
