### ISSUE TITLE
Simulating clock rising trigger: What is wrong with my circuit?

### ISSUE THREAD

**Issue by trungdq88** [hneemann/Digital#342]
I'm trying to simulate the clock rising trigger. It works for the built-in D Flip Flop but doesn't work for the one I built with NOR gates. I attached a GIF below.

![3](https://user-images.githubusercontent.com/4214509/65437691-d5fa1180-de56-11e9-8a26-da65d0e8034e.gif)

I really appreciate someone could help me point out what's wrong, thank you.

**Comment by hneemann** [comment]
The principle is correct, but the trigger pulse is too short.
If the circuit is started in "single gate mode", you can observe in detail what happens.
To fix this, the trigger pulse must be extended to at least two gate propagation times.
Instead of using one NOT-gate you could use e.g. three.
The built-in D-flipflop works because it only requires one gate propagation time to switch. The NOR flipflop requires two.

**Comment by trungdq88** [comment]
Very nice! Thank you!
