### ISSUE TITLE
About duplicate routine names

### ISSUE THREAD

**Issue by kEviN1H** [hneemann/Digital#419]
version: v0.24-6-g22aacf0

![无d标题](https://user-images.githubusercontent.com/4837382/74102773-ba7f7100-4b81-11ea-9ec1-28a29c018f18.png)
After each version update, the routine duplicate will report an error. Can I add a suffix or a prefix to the routine

**Comment by hneemann** [comment]
This is how digital works. When a dig file is opened, the folder containing it and all subfolders are scanned, and all file names must be unique, as subcircuits are identified by name only. This is similar to the approach used by LaTeX. 
If a file is saved directly in the "examples" folder, these errors will occur because the file names in the subfolders of the "examples" folder are not unique. Maybe I should make the file names used unique to avoid this message.

See also #192, #33
