### ISSUE TITLE
rpm attempt and maven plugin error

### ISSUE THREAD

**Issue by copart** [hneemann/Digital#420]
Hi,

I am trying to create a rpm (spec) in Fedora to package Digital. However, I am not too familiar with Maven.

I was getting errors on the rpmbuild on the same plugin as shown below.

To get the following, I tried to run "mvn install"

However, I really want to be able to create an rpm:

Error:
[maven-err.txt](https://github.com/hneemann/Digital/files/4178903/maven-err.txt)

**Comment by hneemann** [comment]
The Maven configuration attempts to extract the version number from the git repo in order to add the version to the help dialog and the distribution. I expect that you don't get the sources by "git clone" but by downloading the sources as a zip or tar which means the git repo is missing.
In this case you have to provide the correct version number by a command line argument.

Please refer to issue #289 to see how this can be done. And please make sure that the correct version number is always set.

**Comment by copart** [comment]
Thank you! I am closing.
