### ISSUE TITLE
whether the monoflop component is working?

### ISSUE THREAD

**Issue by itviewer** [hneemann/Digital#442]
I am learning and trying to translate the description of this component. However, the behavior and description of the component are found to be inconsistent. 
Is the component working normally or How to use this component?

![深度截图_选择区域_20200413110922](https://user-images.githubusercontent.com/1397840/79089326-57c07680-7d78-11ea-8e44-e023a26d7586.png)

**Comment by hneemann** [comment]
After a monoflop has been set, it is automatically cleared when a certain amount of time has passed. Since the simulator does not know real time, a clock is required somewhere in the circuit to determine the set-time.
This time is then given in clock cycles of the existing clock. You can imagine that there is a hidden additional clock input on the monoflop connected to the clock generator, where the visible clock input is only used to set the monoflop and not to determine the duration. It is a somewhat unconventional implementation, but it helps to imagine the working principle of a monoflop. In a real monoflop the duration is set with a resistor and a capacitor.

![z](https://user-images.githubusercontent.com/7190563/79104973-fc8a8600-7d6f-11ea-9a13-f04caee7e306.png)
