### ISSUE TITLE
Help tu use pause component

### ISSUE THREAD

**Issue by abnerbarros** [hneemann/Digital#520]
How to use the pause component? I inserted the component in my project but the Run to Break button is not being activated.

![image](https://user-images.githubusercontent.com/47617233/94282490-4930da80-ff26-11ea-9643-be2df461cbe6.png)

**Comment by hneemann** [comment]
The break component is used to clock the circuit forward to a certain condition. It is not intended to be used if the real time clock is activated. The intended usage is to start the circuit in "non real-time mode" and then instead of clocking the circuit forward click by click to the condition you want to investigate, you are able to clock the circuit forward to this condition automatically.

The stop component simply stops the simulation like the stop button does.

**Comment by abnerbarros** [comment]
It stay confuse for me yet, may you send me one example?

**Comment by hneemann** [comment]
Open the attached circuit:

At first:
1. Start the simulation, the "Run to Break" button is enabled. (Directly to the right of the Start button.)
2. Set en to high.
3. Clock the circuit to a rising edge of Q3 by clicking on the clock component multiple times.

Now:
1. Start the simulation again.
2. Set en to high.
3. Click on the "Run To Break" button.

[cntBrk.dig.zip](https://github.com/hneemann/Digital/files/5287877/cntBrk.dig.zip)

**Comment by abnerbarros** [comment]
This is the problem, the "Run to Break" button   and F7 command always stay disabled for me. 
![image](https://user-images.githubusercontent.com/47617233/94378210-12152180-00fe-11eb-8276-77b4e94b6802.png)
I just open your file and make this printscreen.

**Comment by abnerbarros** [comment]
Great, now it wok fine. Thanks so much.
