### ISSUE TITLE
Clock speed

### ISSUE THREAD

**Issue by PaulKappmeyer** [hneemann/Digital#823]
Is there a way to adjust the speed of the clock while the simulation is running?

**Comment by hneemann** [comment]
So far, this is not possible.

**Comment by PaulKappmeyer** [comment]
Do you think this could be added?
I don’t think that there are that many use cases, but I think it could be a nice feature still.

**Comment by hneemann** [comment]
This is not quite so simple, since different implementations of the clock are used for different clock speeds. For example, at high clock speeds, the simulation runs in its own thread, fully utilizing one core, and the GUI thread's access is synchronized accordingly. It is not so easy to switch in between in the running simulation.
I don't think I want to add variable clock rates.

**Comment by YulienPohl** [comment]
This problem can be solved by a variable clock divider containing a counter and a buffered output to avoid hazards.
[Variable Clock Divider.zip](https://github.com/hneemann/Digital/files/7190265/Variable.Clock.Divider.zip)

**Comment by hneemann** [comment]
@YulienPohl 
What a simple solution to the problem! :smile:
I should have thought of it myself! Thanks for pointing this out! :+1:
