### ISSUE TITLE
Issues with opening a file (v0.27 / v0.28)

### ISSUE THREAD

**Issue by PaulKappmeyer** [hneemann/Digital#826]
![Issue](https://user-images.githubusercontent.com/42696082/133111472-0e90c589-914a-4cd7-a969-9e361b98b586.png)
![Version](https://user-images.githubusercontent.com/42696082/133111490-5823650d-6c7e-4182-a59e-2204fe6bce54.png)

When trying to open some files with v0.27 I get this issue. But I'm able to open these files with the latest release v0.28.

**Comment by hneemann** [comment]
This is due to #824.
If storing a ROM in 0.28 the data is RLE encoded to keep the dig files small.

This is not a problem at all if a file written with 0.27 is opened with 0.28. But if you save a file with 0.28, then the file may not open with 0.27. I always try to keep Digital backward compatible, which is also the case now, but forward compatibility usually can't be made possible
