### ISSUE TITLE
Toggle real-time-clock

### ISSUE THREAD

**Issue by PaulKappmeyer** [hneemann/Digital#843]
Hello,
I’m wondering if it could be possible to add a keyboard shortcut for toggling the real-time-clock while the simulation is running.
Since there is already a shortcut for single-stepping the clock (C Key), it would be very helpful to be able to stop the clock in the simulation at some point and single-step the program.

**Comment by hneemann** [comment]
Since the synchronization is different in the real-time clock mode and in the single-step clock mode, this is difficult to implement. 
But you can use the break component. This way you can define a condition, automatically cycle the circuit until the condition is met and then continue in single step mode. It almost feels like a breakpoint in a programming language. In my opinion debugging is also easier, because it always stops at a defined point.

**Comment by PaulKappmeyer** [comment]
So I’m trying to build Ben Eater’s 8-Bit Pc with Digital, which is why I like the idea of changing the clock-mode while simulation.
But at the moment I’m using this circuit, which seems like a good compromise.
![Clock](https://user-images.githubusercontent.com/42696082/135129944-baa740e9-b26a-46e7-b64a-58d64ddde84c.png)

Thanks for your answer!
