### ISSUE TITLE
Unable to run Analysis with flip-flop

### ISSUE THREAD

**Issue by reifsnyderb** [hneemann/Digital#892]
When creating a logic circuit, I am unable to run an Analysis with either a flip flop or NOR gates set up to function as a flip flop.  Without running an analysis I am unable to create the files to flash an ATF1504.

**Comment by reifsnyderb** [comment]
File attached....

[600 XLM R08 MMU.zip](https://github.com/hneemann/Digital/files/7874427/600.XLM.R08.MMU.zip)

**Comment by hneemann** [comment]
The analysis algorithm is not able to recognize a flip-flop constructed from simple gates and to replace it with a corresponding one. Therefore, the flip-flops that are available as built-in components must be used. The built-in D, T and JK flip-flops can be used. RS-flip-flops cannot be used due to the inherent instability.

**Comment by reifsnyderb** [comment]
Got it working.  Thank you!
